# Generated by Django 4.1.2 on 2022-10-07 23:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('remove_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=100, null=True, verbose_name='파일 이름')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='파일 uuid')),
                ('mime_type', models.CharField(max_length=100, null=True, verbose_name='파일 이름')),
                ('file_type', models.IntegerField(choices=[(0, '이미지'), (1, '일반 파일')], null=True, verbose_name='파일 타입')),
                ('size', models.IntegerField(null=True, verbose_name='파일 사이즈')),
                ('path', models.FileField(upload_to='', verbose_name='파일 경로')),
                ('duration', models.BigIntegerField(default=0, verbose_name='영상 길이')),
            ],
            options={
                'verbose_name': 'files',
            },
        ),
    ]
