# Generated by Django 4.1.2 on 2022-10-08 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar', to='file.files', verbose_name='아바타 그림파일'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(1, '일반 회원'), (101, '판매자'), (256, '슈퍼관리자')], default=False, verbose_name='회원 레벨'),
        ),
        migrations.AddField(
            model_name='user',
            name='modify_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='폰 번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='remove_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
